### ISSUE TITLE
tide-fix imports and relative parts

### ISSUE THREAD

**Issue by ksjogo** [ananthakumaran/tide#129]
tide-fix will insert a path relative to the root/tsconfig.json and not relative to the file where the path is inserted in.
E.g. projects looks like
```
tsconfig.json
src
->Some.ts
->Thing.ts
```
Writing `new Thing();` inside `Some.ts` and then doing `tide-fix` will insert `"src/Thing"` as import path instead of the right `"./Thing"`.

**Comment by josteink** [comment]
Thanks for the bug-report (and thanks for using this new feature I added!)

I'm not able to reproduce this issue myself. Depending on your setup, I'm not even sure that's actually incorrect.

Anyhow I'm pretty sure it's not a bug in `tide`:

* The changes done to your code (including file-names and paths) are not generated by `tide`, but by `tsserver` . This means that `tsserver` (that is, TypeScript itself!) thinks that this is a valid way to import your module. Are you saying TypeScript is wrong? :)
* What happens if you try to compile this with `tsc` from the command-line? Does it report this as a compilation-error of sorts? If not, does this result in bundling errors or runtime errors?
* Do you have a `package.json` in a *different folder* than `tsconfig.json`?

Hopefully inspecting your setup carefully can help us find the source of this oddity.

**Comment by ksjogo** [comment]
Ok, it seems that typescript thinks it is fine to declare the import like this and tsc on its own will work but webpack won't like it afterwards. Adding ```
    resolve: {
        extensions: [".ts", ".tsx", ".js"],
        alias: {
            "src": path.resolve("./src")
        }
    },
```
inside the webpack config fixes it.

**Comment by eastwood** [comment]
For anybody that stumbles across this, I had to modify my module import settings:
```
  (setq-default tide-user-preferences '(:importModuleSpecifierPreference "relative" :includeCompletionsForModuleExports t :includeCompletionsWithInsertText t :allowTextChangesInNewFiles t))
```
This forces it to relative pathing.
