### ISSUE TITLE
tide-project-name is inadequate as a key into tide-servers

### ISSUE THREAD

**Issue by lddubeau** [ananthakumaran/tide#131]
Setting aside details that are irrelevant to the current discussion, `(tide-project-name)` computes a project name by looking at the closest `tsconfig.json` up the filesystem hierarchy and taking the name of the directory that immediately contains the json file so if I have a file under the same directory as the following `tsconfig.json`:

    /home/foo/great-lib/src/tsconfig.json

The `tide-project-name` is `"src"`. So far so good but then I open a file for which the relevant `tsconfig.json` is:

    /home/foo/other-great-lib/src/tsconfig.json

The `tide-project-name` is *also* `"src"` so the files in the 2nd project will be processed using the configuration of the 1st project. Confusion ensues.

Seems to me that the key into `tide-servers` should be unique. An absolute path perhaps?

I see that `(tide-project-name)` is used as a key elsewhere and I suspect the problem described above with `tide-servers` recurs in those cases, but I have not examined each case in details.

**Comment by ananthakumaran** [comment]
I had assumed that `tsconfig` would always be placed in the root folder, but as you mentioned, many use it at per folder level. 

`tide-project-name` is currently used both for unique id & for display purposes. Perhaps, we could add another function named `tide-project-id` and use it as unique id. PR to fix this issue would be great. Otherwise, I will try to look at it this weekend.

**Comment by josteink** [comment]
From what I can tell `tide-project-name` is only used UI-wise in very limited contexts, which are mostly technical/logging-related anyway:

* https://github.com/ananthakumaran/tide/blob/master/tide.el#L391
* https://github.com/ananthakumaran/tide/blob/master/tide.el#L406

I'm not sure it's worth creating a separation between name and ID over this. Using the full path instead of just the folder as the ID is OK for me, unless you have crazy long paths.

Basically all I changed was this:

````elisp
(defun tide-project-name ()
  (directory-file-name (tide-project-root)))
````

It's also worth noting that this issue is about the current ID not being unique. As such being first informed that `"(src) tsserver is starting..."` and then later `"(src) tsserver is starting..."` would seem strange IMO.

I vote for simply replacing the `tide-project-name` function with a less clever one (like the one I did above) and calling it a day.

**Comment by ananthakumaran** [comment]
```elisp
(defun tide-project-name ()
  (let ((full-path (directory-file-name (tide-project-root))))
    (concat (file-name-nondirectory full-path) "-" (substring (md5 full-path) 0 10))))
```

leads to

```
(core-558ede439b) Starting tsserver...
(core-558ede439b) tsserver server started successfully.
```

It's short and unique. @josteink  What do you think?

**Comment by josteink** [comment]
That's pretty good too. I'm fine with that.

**Comment by lddubeau** [comment]
The full path solution has the advantage of being clear as to what specific location is meant, at the cost of perhaps being a pain when long paths are involved. The md5 solution has the advantage of being resilient in the face of long paths at the cost of not being immediately clear regarding what location is being affected. You have to take the project name and do some Lisp evaluations before you can get the full path out of it.

Ultimately, my wish would be to see the value used as a key into hashes be decoupled from what is shown to the user, and for the user side of things do something like what [`uniquify`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Uniquify.html) does for buffer names. But I don't know how reusable `uniquify` is, and this may turn out to be more work than can be devoted to the issue at this time.

Other than that, I have a slight preference for the md5 approach.

**Comment by ananthakumaran** [comment]
fixed in master. Also, regarding something like `uniquify`, I would be OK to accept a PR, provided the implementation is simple, as we don't use the project-name for anything important.
