### ISSUE TITLE
Duplicate entries in imenu

### ISSUE THREAD

**Issue by Eoksni** [ananthakumaran/tide#145]
After running `(tide-setup)` I get duplicate entries for each function in `imenu`:
![image](https://cloud.githubusercontent.com/assets/2010503/25843825/c98f1542-34d2-11e7-8f96-35d04df26be2.png)

**Comment by josteink** [comment]
To me it sounds like some code is getting run twice here, and the first thing I'd like to eliminate is that it could be due to any local configuration issues.

If you start Emacs without any site files or custom config (`emacs -Q`) can you still reproduce this issue?

**Comment by Eoksni** [comment]
with this:
`emacs -Q check-imenu.js`
```elisp
(package-initialize)
(tide-setup)
(ivy-mode)
```
`M-x imenu`
I get duplicates, but if I turn off `ivy-mode` all is fine and duplicates are gone. `counsel-imenu` (its an extension to ivy) also shows duplicates. 

I guess then it is a bug in ivy? Seems super weird, never had any dup problem with ivy in other places.

**Comment by josteink** [comment]
I've tested with helm, and I get the same results. But looking at our imenu-code, it's really short and to the point:

https://github.com/ananthakumaran/tide/blob/master/tide.el#L1106-L1121

What I do suspect is that something shows up twice, because the this entity may be reported several time as a *different* kind of entity.

I therefore tried to attach a debugger at the first point where we start processing data after receiving them: https://github.com/ananthakumaran/tide/blob/master/tide.el#L1106-L1109

And that's the smoking gun. Basically `hello()` is (by tsserver) reported as a local function (in scope) and also a function nested in the global scope. This results in a duplicate when we flatten the list. And we don't do any work to try to eliminate those duplicates.

In the meantime, I've never had issues with duplicates when working with bigger modules where I've been "proper" about structuring things in classes etc.

I don't have time to create a fix anytime soon, so if you feel like sending in a patch, that's cool, and I'll be more than happy to review it.

**Comment by ananthakumaran** [comment]
@Eoksni can you test it again? it should be fixed in master.

**Comment by Eoksni** [comment]
Yes, it works! Big thanks.
