### ISSUE TITLE
Support for source maps?

### ISSUE THREAD

**Issue by raxod502** [ananthakumaran/tide#174]
With Tide and Flycheck, I have excellent support for debugging compile-time errors. But when I have a runtime error, I have to take a rough guess at how the line numbers and symbols will translate. This is pretty much always good enough, but seems a little clumsy.

Would it be possible for Tide to offer some kind of go-to-JS-line-number which would use the generated source map in order to go to the correct line number in the TypeScript file?

**Comment by josteink** [comment]
This kind of functionality really would be usefully in many cases outside typescript and tide, and as such I don't think it belongs here. 
Other examples where similar functionality would be useful:
- transpiling with babel- clojurescript/coffeescript- script-bundling with webpack or browserify- etc
I honestly think this problem would be best solved outside tide, so that it can be reused for more Emacs-modes. 
		
		

		--
Jostein Kjønigsen 
jostein@kjonigsen.net
	





On Fri, Jul 14, 2017 at 10:06 PM +0200, "Radon Rosborough" <notifications@github.com> wrote:












With Tide and Flycheck, I have excellent support for debugging compile-time errors. But when I have a runtime error, I have to take a rough guess at how the line numbers and symbols will translate. This is pretty much always good enough, but seems a little clumsy.


Would it be possible for Tide to offer some kind of go-to-JS-line-number which would use the generated source map in order to go to the correct line number in the TypeScript file?

**Comment by raxod502** [comment]
Oh, I hadn't realized that the source map format was standardized beyond just TypeScript. In that case, perhaps http://lisperator.net/blog/source-maps-for-emacs/ would be a good starting point for a new library.

**Comment by lddubeau** [comment]
I agree with @josteink that this is really something beyond the confines of tide.

In my experience, the place where to fix a mapping problem is not Emacs at all. In many cases, the machinery to get mapping from JS locations to TS locations is already there but it does not have the information it needs. A classic example is running Karma with a `files` configuration that does not serve the map files to the browser: even though everything is there, the browser is not able to map locations because it cannot load the map files. Similar issues can occur through misconfiguring tools like Webpack or Browserify, etc.

Or sometimes some VMs need a bit of help to perform the mapping. Node, is an example of [this](https://github.com/evanw/node-source-map-support).

The only time I recall not being able to work around a mapping problem was a rather particular use-case scenario where I was running browser code in [jsdom](https://github.com/tmpvar/jsdom) in a test suite. It was too narrow a use-case scenario to be worth my time fixing but I suspect one of the issues above was the culprit.

All this to say that if I ran into this issue, I'd first be looking at the build chain or the VM for a solution. At the same time, I'm pragmatic enough to know there may be some cases where getting all the pieces to work is not practical (or even impossible if constrained to using an old VM), and a workaround running in Emacs may be useful to deal with such cases.

**Comment by raxod502** [comment]
I found https://github.com/evanw/node-source-map-support and it does look like a better solution for my use case (stack trace is printed, I need the `.ts` line numbers instead of the `.js` ones). Thanks!
