### ISSUE TITLE
Question: Is highlighting errors in plain js files with jsdoc comments possible?

### ISSUE THREAD

**Issue by leo-shopify** [ananthakumaran/tide#189]
With a `tsconfig.json`:
```js
{
  "compilerOptions": {
    "target": "es6",
    "strict": true,
    "allowJs": true,
    "checkJs": true,
    "noEmit": true
  }
  "files": ["my.js"]
}
```
and `my.js`:
```js
/**
 * @type {string}
 */
let a = 'string';
a = 404;
```
I was expecting to get the line marked with the error:
> my.js(5,1): error TS2322: Type '404' is not assignable to type 'string'.

in `a = 404;`, which is what happens when running `tsc` directly.

Is this currently possible?
I'm using the version in [melpa](https://melpa.org/#/tide).

Thanks!

**Comment by josteink** [comment]
Why is my-file JavaScript and not .ts?

Tide together with flycheck should pick up any and all such errors.

**Comment by lddubeau** [comment]
As I recall, unless you take special care of setting a path for `tsserver`, tide will use the stock `tsserver` that it includes among its files, which according to what I see on github is in the 2.4 series and thus would not report that error because that's a feature introduced with 2.5. You'd have to change the path to the `tsserver` included in the TypeScript version you installed.

@josteink The OP is using a new [feature](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#type-assertioncast-syntax-in-checkjsts-check-mode) in 2.5, designed specifically for JS code being processed by `tsc`.

**Comment by leo-shopify** [comment]
It's useful to annotate plain js files with jsdoc types in code bases that are not using typescript, but still get type checks, like a linter. it's a feature from typescript 2.4 https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files

**Comment by lddubeau** [comment]
@leo-shopify The support for `@type` is a 2.5 feature.

**Comment by leo-shopify** [comment]
@lddubeau Good suggestion. Let me try that and I'll report back.

**Comment by leo-shopify** [comment]
Yes, that was it. Changing the path to the exe, as per the FAQ did it.
```elisp
(setq tide-tsserver-executable "node_modules/typescript/bin/tsserver")
```
Thank you very much. I can add it to the readme tomorrow.

**Comment by josteink** [comment]
I guess it's time for someone to update the shipped tsserver again :)

**Comment by leo-shopify** [comment]
:) I'll take a stab at it.

**Comment by lddubeau** [comment]
Upgrading the `tsserver` is fine, but I've opened an issue (#190) to discuss another approach.
