### ISSUE TITLE
Add tslint --fix for all file

### ISSUE THREAD

**Issue by danielpa9708** [ananthakumaran/tide#281]
Hello, I erased the issue template for this is not a bug: what do you think about having a command for fixing all tslint errors in the file (ie `tslint --fix $(buffer)`) ?.

I used to have a shortcut in my .emacs for running this command and reverting the buffer, and this is really helpful for some tslint rules like `ordered-imports`, etc

**Comment by josteink** [comment]
Not sure to be honest about this one, to be honest. So far we've been pretty consistent w.r.t. separation of responsibilities:

* typescript-mode: syntax highlighting and indentation
* tide: tsserver-client to provide intelligent feedback and navigation.

Error-reporting has really been handled through tsserver... But we've had no place for linting.

This has kept dependencies simple, and platform-specific code to a minimum. Expanding on that might make life ... less simple.

Suddenly something may or may not work in tide, because you don't have tslint installed? That sucks.

If we ship tslint with tide (like we do with tsserver, as a fallback), we may end up using a different tslint version than the user expects. And we'll need more code to resolve tslint... And stuff and stuff.

So adding additional dependencies to tide (like tslint) is not something I'd like to do if it can be avoided.

So what other options are there?

I can only assume flycheck may provide tslint feedback (as it does does for other major-modes)... Would adding a more generic "fix-linting-errors" function be more appropriate there? (Where it already depends on tslint)

Wouldn't that make more sense?

Opinions?

**Comment by ananthakumaran** [comment]
As @josteink explained, we try not to add any feature that's not directly tied to `tsserver`. Otherwise, it's difficult to draw the line. I have custom config for applying linter fixes and it's quite useful, but I believe tide is not the place to add such utilities.

```elisp
(defun eslint-fix-file ()
  (interactive)
  (shell-command (concat "eslint --fix " (buffer-file-name)))
  (revert-buffer t t))
```
That said, we could definitely expose more hooks like `tide-post-code-edit-hook` if it could help other tools to do their work.
