### ISSUE TITLE
[Question] Reason to choose Tide over lsp-mode?

### ISSUE THREAD

**Issue by ianpan870102** [ananthakumaran/tide#361]
Looking at the commands and features, I see little difference between Tide and the Javascript/Typescript support in lsp-mode. For me personally, I currently use lsp-mode in c/c++, python, javascript/typescript etc. It'd be nice to integrate everything with one lsp package. But I'm also open to using Tide if it does provide better support than the current state of lsp-mode, hence the title.
Thank you in advance.

**Comment by josteink** [comment]
Speaking as one of the contributors of `tide` (but not the main author and "owner" of the project), I have to say I see `lsp-mode` as the shining future of everything programming-related in Emacs.

There's no doubt in my mind that in the future people will find and prefer `lsp-mode` over having to maintain a million language-specific options. It's really a no-brainer. That said, the current state of language support in `lsp-mode` is not perfect.

I've tried to assist getting better C#-support in `lsp-mode`, but the implementation there still has bugs not found in the language-specific package `omnisharp-emacs`. So for production-needs, I still need to rely on that over `lsp-mode`.

In the same vein I've tried in the past to add basic `typescript-mode` support to `lsp-mode`, but I met some issues which made me stall the project until further...

If everyone involved in this project can agree that `lsp-mode` is a very worthwhile long-term goal... Maybe some of the effort spent here could instead be used to improve `lsp-mode`? And then we could probably get up `lsp-mode` to an acceptable state for regular typescript-development in not too long time. 

For now though, I find `tide` highly reliable in my day to day work, and `lsp-mode` not so much... So currently I'd recommend `tide` over `lsp-mode` for typescript-projects.

Ofcourse these are just my experiences and my 2 cents. YMMV.

**Comment by ianpan870102** [comment]
@josteink Thank you for taking the time to write this comprehensive reply, I'll close this issue now and experiment with both packages more for myself!

**Comment by lddubeau** [comment]
@ianpan870102 I agree with most of what josteink said. I use `tide` because it just works and whenever I looked at `lsp-mode` (including just now) I found issues that are already solved in `tide`.

Let me ask you this. Suppose you are working on multiple TypeScript projects and they rely on different versions of TypeScript. For logistical reasons you cannot all upgrade them to the same version of TypeScript. How do you configure `lsp-mode` so that you can work on these projects simultaneously and so that the feedback you get in Emacs respects the TypeScript version used by each project? Looking at the available documentation of `lsp-mode` and the associated language servers, I'm not seeing a clear path towards a configuration that does this. [This server](https://github.com/theia-ide/typescript-language-server) at least allows setting a path to `tsserver`. Great! But I don't see how that would allow supporting multiple versions *simultaneously*.

Tide already supports this. In most cases, it happens transparently *without requiring any special configuration*. Really! I can clone a project off of github, do `npm install` at the top level of that project, and open any TS file from that project and tide will automatically pick up the right `tsserver`. For those projects that have special requirements, we've documented the configuration variables that can be set.

**Comment by josteink** [comment]
Just to add to this otherwise "closed" issue...

I just updated to latest `lsp-mode` and it now offers to auto-install `tsserver`, and actually provides working auto-completions and type-information!

Maybe it will be a worthy replacement for `tide` in a year or two :smile:

**Comment by mpereira** [comment]
Hey @ianpan870102, did you end up staying with LSP mode for JS? I found some things lacking, like auto-completion.

**Comment by ianpan870102** [comment]
Yes, currently I'm using lsp-mode with JS/JSX. I also found web-mode to give the best syntax highlighting, so I've added *.js to web-mode too.
In general, I seldom use autocompletion features and care more about "go-to definitions", for which lsp has served me well.
Whenever I feel the need of a 'really intelligent' IDE experience for JS dev, I fire up Visual Studio Code -- gotta use the best tool for the job.

**Comment by mpereira** [comment]
I appreciate the context, thanks @ianpan870102!

**Comment by ianpan870102** [comment]
@mpereira No problem!

**Comment by Invertisment** [comment]
I've tried LSP mode for TS and it has an issue with importing inside monorepo.
I worked with that setup for about 2 months and it works inside a single project.
But now I have to switch to tide because of the monorepo project import issue.

So currently I'm trying to set up so that popups wouldn't appear and cover my code and I can't find the variable for that.
I use spacemacs and they did configure LSP to work with auto-completion layer -- which is really great. And as tide is not configurable this way I have to find a workaround. 

I really got used to how LSP mode can display code fixing hints and other messages at the right side of the code window without covering my code:

tide:
![Screenshot at 2020-08-18 13-22-53](https://user-images.githubusercontent.com/1641263/90502452-856a6180-e156-11ea-8d5a-45aca9090cf6.png)

lsp-layer for spacemacs with auto-completion `auto-completion-enable-help-tooltip nil`
![Screenshot at 2020-08-18 13-24-04](https://user-images.githubusercontent.com/1641263/90502503-987d3180-e156-11ea-9715-a7224b6c598c.png)
