### ISSUE TITLE
Errors are sometimes reported at the wrong position when viewing tab-indented files.

### ISSUE THREAD

**Issue by kuba-orlik** [ananthakumaran/tide#366]
When submitting issues to this project, please include the following information.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [x] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [x] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: 20200111.1236
- TypeScript: 3.8.2
- Emacs: 26.3

## Steps to Reproduce the Bug

Sometimes when an error is found in my code, the red underline that points out where the error is is actually to the right of where it actually should be. Here's a snippet of code that triggers the issue:

```ts
class ABC {
	constructor(colors_config: IColorsConfigObject) {
		for (const color_role of ["title", "body"]) {
			for (const color_variant of ["primary", "secondary"]) {
				const variant_name = `${variant_a}-text-on-${variant_b}`;
			}
		}
	}
}
```

![screenshot of the misaligned highlight](https://user-images.githubusercontent.com/2697916/76143009-1ba84080-606b-11ea-8807-44d5342d3c1e.png)

After replacing all tabs in the file with spaces, the underlines are back at the correct position: 

![2020-03-07_13-00](https://user-images.githubusercontent.com/2697916/76143022-42667700-606b-11ea-9f27-b73fb4adb114.png)

## Expected Behavior

The squiggly lines that point at errors in code should be always be properly aligned when the file uses tabs for indentation.

## Actual Behavior

The squiggly lines that point at errors in code sometimes are not properly aligned when the file uses tabs for indentation.

**Comment by lddubeau** [comment]
I confirm that this is a real problem with `tide`. The issue is in `tide-column`. The function seems to want to compute an offset from the start of the line. If I'm correct, then `current-column` is **not** the right function to use to get a column number because it measures in visual columns. Suppose you set `tab-width` to 8, and create a line that starts with a tab  and move point after the tab, the column number is going to be 8, but your offset from the start of the line is 1.

This being said, I don't know what overall problem this function is meant to fix. It is used in only one place in `tide.el` and if I remove the call to it, error messages in my buffers are still reported correctly. Maybe there's some edge case it was aiming to fix and I'm just not hitting it. If that's the case, then the function should be documented to explain what problem is is meant to fix so that future contributors don't have to figure it out all over again. I've seen similar code in `flycheck.el` but the code there was very careful to avoid moving over the next line if an offset into a line was too large. (It was essentially normalizing column numbers that don't make sense.) The code in `tide` does none of that: if `offset` is greater than than the line length, it'll just wander onto the next lines and report an bogus column number.

So right now I'd just remove `tide-column`, but I'm concerned there may be a scenario I'm missing. I'd like to think it was not added for no reason.

@ananthakumaran When I look at the log it seems you are the originator of that function. Got any hints?

**Comment by ananthakumaran** [comment]
@lddubeau I don't remember the exact reason. My guess is, I might have mistaken the column for emacs column number without reading the flycheck documentation.

```
`column' (optional)
     The column number the error refers to, as number.

     For compatibility with external tools and unlike Emacs
     itself (e.g. in Compile Mode) Flycheck uses _1-based_
     columns: The first character on a line is column 1.

     Occasionally some tools try to proactively adapt to Emacs
     and emit 0-based columns automatically.  In these cases, the
     columns must be adjusted for Flycheck, see
     `flycheck-increment-error-columns'.

     If nil, the whole line is highlighted.
```

Given that flycheck also sanitizes the column number, I will remove the call to tide-column
