### ISSUE TITLE
How to work with yasnippet and improve the speed of completion

### ISSUE THREAD

**Issue by glepnir** [ananthakumaran/tide#368]
When submitting issues to this project, please include the following information.

## Checklist

- [ ] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [X] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [X] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [ ] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [ ] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [ ] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: the latest
- TypeScript:3.7.2
- Emacs:28

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug
 First of all , i config the `company-idle-delay` to `0` and `tide-sync-request-timeout` to `0`
1. open a react project 
2. input `console.`
3. It has a noticeable delay after the input `.`
4. company-tide cant work with company-yasnippet

## Expected Behavior

1. improve the speed of completion.
2. work with company-yasnippet
## Actual Behavior

1. speed
![test](https://user-images.githubusercontent.com/41671631/76281832-35e35800-62d1-11ea-9824-e807d6e7cf33.gif)
2.  yasnippet
![test](https://user-images.githubusercontent.com/41671631/76282050-8e1a5a00-62d1-11ea-99b5-d7dd0c80409d.gif)

**Comment by josteink** [comment]
Hey Stephen.

Thanks for bug-report. Just to make sure I understand you properly: Are you saying that `company-yasnippet` is not working when `tide` is enabled because of the performance of `company-tide` completions?

As someone not deeply into `company-mode`, I'm not going to debate that, but it *does* sound strange.

As for `tide`, most of the stuff you see happening there is actually done by TypeScript's own `tsserver` behind the scenes.

Looking at the code, I can't see any artitficial delays in sending out a call for completions in the `company-tide` implementation, so my guess is that this delay you experience is time spent in `tsserver` itself before it provides a reply back to `company-tide`. And `tide` can't fix that.

Unless you can demonstrate that this is a bug in `tide`, not a general problem with `tsserver`, I'm not sure what we can do to help you.

Maybe this is better fixed in `company-yasnippet`? Maybe it should be more tolerant of longer completion-times?

**Comment by taigacute** [comment]
I'm not quite sure if the time consuming is in tsserver returning the response. I just switched from vim to emacs and coc-tsserver is fast. I will take the time to do a simple test. company-yasnippet works with other company backends, but it's strange that it can't work with tide.

**Comment by ananthakumaran** [comment]
You could enable logs and check how much time is taken by tsserver. https://github.com/ananthakumaran/tide#debugging

**Comment by josteink** [comment]
Could a potential slowness be explained by Emacs having to parse big JSON-structures (which is obviously project sensitive)?

That *has* been an issue in the past, right?

**Comment by taigacute** [comment]
emacs27 had provide a c parser`--janson` to parse the JSON.  Does tide use it will speed improve?
