### ISSUE TITLE
Feature request: Use jansson-backed json de/serialization

### ISSUE THREAD

**Issue by sandinmyjoints** [ananthakumaran/tide#374]
When submitting issues to this project, please include the following information.

## Checklist

- [X] I have searched both open and closed issues and cannot find a duplicate.
- [X] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [X] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [X] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [ ] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [X] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [X] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: all
- TypeScript: all
- Emacs: >=27 

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug

- search tide elisp code for json-serialize, json-parse-string, json-parse-buffer, etc.

## Expected Behavior

- find code that uses these defuns

## Actual Behavior

- no code uses these defuns

Starting in Emacs 27, Emacs has defuns that use a json library written in C, yielding performance gains of up to 15x on json operations -- see https://github.com/emacs-lsp/lsp-mode/issues/210
lsp-mode has implemented feature detection, with fallback to json.el, for example: https://github.com/emacs-lsp/lsp-mode/blob/d89f403fbf629f4c6b95d63115a4959547cea531/lsp-mode.el#L5925-L5937
That seems like a sensible approach that tide could use as well!

**Comment by josteink** [comment]
> Starting in Emacs 27, Emacs has defuns that use a json library written in C, yielding performance gains of up to 15x on json operations

That sounds like a really good improvement. Any PR which implements this in a sufficiently backwards compatible manner is going to be very much welcome.

> see emacs-lsp/lsp-mode#210

Since you're already aware of `lsp-mode`... We've already have a small discussion about that: https://github.com/ananthakumaran/tide/issues/361

As it stands right now (for me at least) I'm trying to move as much of my config and setup to `lsp-mode` simply because that is:

1. a universal solution and
2. clearly where the future lies, and
3. it's fast too! (see https://github.com/emacs-lsp/lsp-mode/issues/210) :smile: 

And for the typescript-projects I currently work on, `lsp-mode` actually seems to work now.

Needless to say, and speaking for myself only, when the day comes that `lsp-mode` handles all my needs without issues, I really don't see the point in effort by maintaining a duplicated lsp-client in the form of `tide`. Basically I'd rather put my effort into building the future, instead of maintaining the past.

The other `tide` co-maintainers may disagree with me on that though :smile:

**Comment by sandinmyjoints** [comment]
My experience with lsp-mode sounds similar to what you described in that thread, except I haven't gone back and tried it out again with js/ts recently. I'll give it another shot. I'm all for merging tide into lsp-mode if it provides feature parity and is fast enough to use without pain.
