### ISSUE TITLE
Custom Indent Break?

### ISSUE THREAD

**Issue by imxinxi** [ananthakumaran/tide#39]
The latest tide release break my custom indent.
I used to set indent to 2 space but now it doesn't work.
The 20160527 version works, so I review the code and found the line 
```
`(:tabSize ,tab-width :indentSize ,typescript-indent-level)
```
modified to 
```
`(:tabSize ,tab-width)
```

Why delete the indentSize ? I found it still useful in tsserver.

**Comment by ananthakumaran** [comment]
Sorry about breaking it.Tide now supports other types of file like tsx, jsx and js. So setting it to `typescript-indent-level` doesn't make much sense in all the cases. I will try to bring it back so that it would work with all the file types. Until then you can use `tide-format-options` to configure the indentSize.
