### ISSUE TITLE
Tide should support a TypeScript repl (via comint)

### ISSUE THREAD

**Issue by josteink** [ananthakumaran/tide#63]
When developing, it's always nice to be able to evaluate code as you move along.

The simplest way to achieve this would probably just to integrate with an existing Type-script repl via Emacs [comint](https://masteringemacs.org/article/comint-writing-command-interpreter). An example of such a comint (for Javascript) is [js-comint](https://github.com/redguardtoo/js-comint).

[tsun](https://github.com/HerringtonDarkholme/typescript-repl) is such a repl for TypeScript.

Would it be possible to make a comint like this ported for `tide`, or would it make more sense to develop as its own package?

**Comment by josteink** [comment]
Reusing js-comint and just hacking around, I made this actually functional package in almost no time:

https://github.com/josteink/ts-comint

It probably needs some cleaning up (as always) but if that is all, I might just keep it as a separate package. I mean... The Emacs way is not intermixing things which can be kept separate, right?

If I decide to keep my own package, I'll just close this issue :)

**Comment by josteink** [comment]
I've created a package of my own for this purpose: https://github.com/melpa/melpa/pull/4295

If you feel this could be relevant to tide or typescript.el or tide, feel free to copy it and integrate it into those packages.

Until then, I'll just keep it a separate package, and consider this issue resolved.

**Comment by ananthakumaran** [comment]
Yes, make sense to keep it as a separate package.

**Comment by sdegutis** [comment]
@josteink Thanks for making ts-comint. You don't have Issues enabled on that repo, and I'm running into a couple of snags using it. I'm guessing that it's probably disabled because of lack of time to devote to bug fixes in open source software, which is completely understandable. One benefit of having the issues feature enabled is that other people then have a central place to discuss issues with each other, and might be able to come up with fixes independently. Just something to consider. Thanks again for doing this initial work.

**Comment by josteink** [comment]
@sdegutis most be an oversight. Enabled now. 

As always, PRs are welcome too :)
