### ISSUE TITLE
Beter syntax highlight using js2-mode

### ISSUE THREAD

**Issue by marcelino-m** [ananthakumaran/tide#69]
I configured tide-mode with js2-mode instead of typescript-mode, the result is much better,
why not use js2-mode that has better syntax highlight?

Thanks for tide-mode :)

![js2-typescript](https://cloud.githubusercontent.com/assets/10197711/19330184/4ab95dcc-90b3-11e6-8ccb-c58700e5cef2.png)

**Comment by ananthakumaran** [comment]
Tide doesn't want to dictate which major mode to use. I should work equally well with both js2-mode and typescript-mode. If you faced any problems with configuring js2-mode, let me know. I will try to fix it.

As for the default mode used in readme, I am not sure about the level of support provided by js2-mode. It might be due to es6 syntax.

**Comment by marcelino-m** [comment]
sorry for the delay,
js2-mode works pretty well but not perfectly. And yes some issues exist with  highlight but is acceptable
Thank for tide, its bery ussefull!!

**Comment by ananthakumaran** [comment]
I am closing this issue. feel free to open an issue if you encounter any problems with tide + js2-mode.
