### ISSUE TITLE
Error using Tide 2.0.6 + Flycheck + Typescript 1.8.7

### ISSUE THREAD

**Issue by nahuel** [ananthakumaran/tide#75]
Saving the file when using tsserver from TS 1.8.7 raises the following error:

```
Error from syntax checker typescript-tide: Unrecognized JSON command: syntacticDiagnosticsSync
```

I think `syntacticDiagnosticsSync` is not present in TS < 2. It will be nice to make Tide check the tsserver version and warn if is an incompatible one.

**Comment by josteink** [comment]
With rapid releases of TypeScript, all of them backwards compatible and most of the new versions bringing general improvements to the tooling and compiler...

Are there any real reasons to sticking to an old version instead of upgrading?

I honestly don't see the case for having `tide` support countless backwards-compatibility levels just to ensure we work with every subset of `tsserver` commands which has ever existed.

I vote for not fixing this, and just advising general upgrades. At worst, people can use a newer `tsserver` for editing (via `M-x customize-group<RET>tide`) than they use for production builds.

**Comment by nahuel** [comment]
I also don't see the case of supporting versions too old, but Tide must warn if the tsserver version is older than the minimum supported.
