### ISSUE TITLE
Jump-to-implementation

### ISSUE THREAD

**Issue by AndyMoreland** [ananthakumaran/tide#97]
Hi!

I work on a project called [tsunami](https://github.com/andymoreland/tsunami) that is symbiotic with `tide`. I use a lot of your private functions and add some extra stuff. Recently I implemented support for the new TS2.1 "goto implementations" language service API here: https://github.com/AndyMoreland/tsunami/commit/70073d55dac7311794ee86019560148fb37b29cf#diff-6ecbb72ef0ea102717543dab4c97cb8eR46.

It's pretty simple, so perhaps it should go into `tide` directly. I use a popup menu UI for displaying the options inline in the buffer, but I don't think `tide` takes a dependency on that library yet.

![screen shot 2017-01-04 at 11 06 16 am](https://cloud.githubusercontent.com/assets/37327/21655188/d5d71c72-d26d-11e6-824f-710f6562ff83.png)

Feel free to use any of the code if you want.

Andy

**Comment by ananthakumaran** [comment]
Cool. Feel free to open PRs if you feel something could be done better in tide. As for goto implementation, tide has no dependency on autocomplete. It has optional dependency on company. Perhaps we could use ido style selection for multiple choices. I will think about it.

**Comment by josteink** [comment]
If we use `completing-read` whatever the user has set as his preference (ido, ivy, helm whatever) will be used.

I agree popups *look* nice, but I think `completing-read` should be preferred over it because popup lacks the fuzzy matching you you can use with helm/ido, and you are constrained to up/down/select style navigation only.

That said: I'd love to see a PR for this functionality in any form, and then worst case scenario we can improve upon it later :)

**Comment by josteink** [comment]
I think I'll take a stab at implementing this myself. Looks easy enough and we have most of the bits we need already.

But in order to avoid excess duplicate code, I'll hold of submitting this until https://github.com/ananthakumaran/tide/pull/118 is merged and mainlined.
